//
//  terms view.swift
//  BaLAncE
//
//  Created by applelab02 on 3/2/26.
//

import SwiftUI
struct termsview: View {
    var body: some View {
   NavigationStack {
       VStack(alignment: .leading, spacing: 12){
           Text("Terms and Conditions")
               .font(.title2)
               .fontWeight(.semibold)
               .foregroundColor(.blue)
               .padding(.bottom, 4)

           ScrollView {
               Text("""
               Welcome to BaLAncE. By using this application, you agree to the following terms and conditions. Please read them carefully.\n\n
               Permissions and Access: To provide core functionality, the app may request access to certain device features and data. This can include: (1) Location Services: Used to enable features that require your approximate or precise location (e.g., activity tracking, region-specific content). (2) Photos/Phone Gallery: Used to let you select and upload images, and to save images generated by the app. (3) Camera: Used to capture photos or videos for features that require direct image input. (4) Contacts: Used to enable features that involve selecting or sharing with people from your contact list.\n\n
               Data Use: Access is requested only when features require it, and you can deny or revoke permissions at any time in your device settings. If you deny a permission, related features may be limited or unavailable. The app processes your data in accordance with our privacy practices and only for purposes described within the app experience.\n\n
               Your Responsibilities: You agree to use the app lawfully and not to misuse content, features, or services. You are responsible for maintaining the confidentiality of your account and device, and for actions taken through your account.\n\n
               Service Changes: Features may be updated, added, or removed at any time. We may modify these terms from time to time; continued use of the app signifies acceptance of the updated terms.\n\n
               Disclaimer: To the fullest extent permitted by law, the app is provided on an “as is” basis without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the app.\n\n
               Contact: If you have questions about these terms or how your data is handled, please contact support from within the app.\n\n
               By continuing to use BaLAncE, you acknowledge that you have read and agree to these terms and conditions, including the permissions regarding location, photo gallery, camera, and contacts.\n
               """)
               .font(.footnote)
               .foregroundColor(.primary)
               .multilineTextAlignment(.leading)
               .padding(.horizontal)
           }

           Spacer()
       }
       .padding()
    }
    }
}
#Preview {
    termsview()
}
